/* =========================================================================
 * Generic dataLayer Snippet — Generated by site-marketing-infra-setup skill
 *
 * For sites NOT on Shopify. Adapt the data source helpers (getPageType,
 * getProduct, etc.) to wherever your platform exposes that data
 * (WordPress globals, custom JS variables, embedded JSON, etc.).
 *
 * Placeholders to replace at generation time:
 *  · {{ SITE_BRAND_NAME }}     → e.g., "Janibell"
 *  · {{ INDUSTRY_MAP_JSON }}   → JS object literal of url-segment → industry
 *  · {{ MODEL_TYPE }}          → "b2b_lead" or "d2c_ecommerce"
 *  · {{ PRODUCT_URL_PATTERN }} → regex string for product pages (default below)
 *  · {{ COLLECTION_URL_PATTERN }} → regex string for collection/category pages
 *
 * Install: paste this entire <script> block into the <head> of every page,
 * AFTER the GTM container snippet.
 * =========================================================================
 */
(function () {
  window.dataLayer = window.dataLayer || [];

  var MODEL = '{{ MODEL_TYPE }}';
  var BRAND = '{{ SITE_BRAND_NAME }}';
  var INDUSTRY_MAP = {{ INDUSTRY_MAP_JSON }};
  var PRODUCT_PATTERN = new RegExp({{ PRODUCT_URL_PATTERN | default: '"/(product|products|p)/"' }});
  var COLLECTION_PATTERN = new RegExp({{ COLLECTION_URL_PATTERN | default: '"/(category|collection|c)/"' }});

  // ---------- Page type detection ----------
  function getPageType() {
    var p = window.location.pathname;
    if (p === '/' || p === '/index') return 'home';
    if (PRODUCT_PATTERN.test(p)) return 'product';
    if (COLLECTION_PATTERN.test(p)) return 'collection';
    if (/\/cart\b/.test(p)) return 'cart';
    if (/\/checkout\b/.test(p)) return 'checkout';
    if (/\/(order|thank-you|success)/.test(p)) return 'purchase_confirmation';
    if (/\/(contact|inquiry)/.test(p)) return 'contact';
    if (/\/(catalog|catalogue|brochure)/.test(p)) return 'catalog';
    if (/\/(about|brand|story)/.test(p)) return 'about';
    if (/\/(blog|news|article)/.test(p)) return 'blog';
    return 'other';
  }

  // ---------- Industry detection from URL ----------
  function detectIndustry() {
    var path = window.location.pathname.toLowerCase();
    for (var key in INDUSTRY_MAP) {
      if (path.indexOf(key) === 0 || path.indexOf('/' + key) === 0) {
        return INDUSTRY_MAP[key];
      }
    }
    return 'OTHER';
  }

  // ---------- Customize: replace these with your platform's globals ----------
  function getProduct() {
    // Example for WordPress + WooCommerce — adapt to your platform.
    if (window.wc_single_product_params) {
      return {
        handle: window.wc_single_product_params.product_id || '',
        title: document.title || '',
        category: '',
        price: 0
      };
    }
    // Fallback: read from JSON-LD on page
    var ld = document.querySelector('script[type="application/ld+json"]');
    if (ld) {
      try {
        var data = JSON.parse(ld.textContent);
        if (data['@type'] === 'Product') {
          return {
            handle: (data.sku || data.productID || '').toString(),
            title:  data.name || '',
            category: (data.category || '').toString(),
            price:  parseFloat((data.offers && data.offers.price) || 0)
          };
        }
      } catch (e) {}
    }
    return { handle: '', title: '', category: '', price: 0 };
  }

  function getCart() {
    // Override with your platform's cart accessor. Returns { items: [], total: 0 }.
    return { items: [], total: 0 };
  }

  function isLoggedIn() {
    // Override with your platform's auth check.
    return !!document.querySelector('[data-logged-in], .logged-in, body.logged-in');
  }

  // ---------- Common page-level push ----------
  var pageType = getPageType();
  window.dataLayer.push({
    page_type:     pageType,
    page_location: window.location.href,
    page_path:     window.location.pathname,
    industry:      detectIndustry(),
    user_logged_in: isLoggedIn()
  });

  // ---------- Product page (PDP) ----------
  if (pageType === 'product') {
    var prod = getProduct();
    window.dataLayer.push({
      event: 'view_item',
      product_handle: prod.handle,
      product_title:  prod.title,
      product_category: prod.category,
      industry: detectIndustry(),
      ecommerce: {
        currency: 'USD',
        items: [{
          item_id:   prod.handle,
          item_name: prod.title,
          item_brand: BRAND,
          item_category: detectIndustry(),
          price: prod.price
        }]
      }
    });

    // B2B: CTA click capture
    if (MODEL === 'b2b_lead') {
      document.addEventListener('click', function (e) {
        var el = e.target.closest('a, button'); if (!el) return;
        var txt = (el.textContent || '').trim().toLowerCase();
        if (/contact\s*us|request\s*a?\s*quote|get\s*a?\s*quote/i.test(txt)) {
          var section = el.closest('section, [class*="section"]');
          var sectionName = section ? (section.className.split(' ')[0] || 'pdp') : 'pdp';
          window.dataLayer.push({
            event: 'request_quote_meta',
            source_section: sectionName,
            product_handle: prod.handle,
            industry: detectIndustry()
          });
        }
      });
    }

    // D2C: Add to cart capture
    if (MODEL === 'd2c_ecommerce') {
      document.addEventListener('click', function (e) {
        var el = e.target.closest('button[name=add], [data-add-to-cart], .single_add_to_cart_button'); if (!el) return;
        window.dataLayer.push({
          event: 'add_to_cart',
          ecommerce: {
            currency: 'USD',
            value: prod.price,
            items: [{
              item_id:   prod.handle,
              item_name: prod.title,
              item_brand: BRAND,
              price: prod.price,
              quantity: 1
            }]
          }
        });
      });
    }
  }

  // ---------- Cart page ----------
  if (pageType === 'cart' && MODEL === 'd2c_ecommerce') {
    var cart = getCart();
    window.dataLayer.push({
      event: 'view_cart',
      ecommerce: {
        currency: 'USD',
        value: cart.total,
        items: cart.items
      }
    });
  }

  // ---------- Contact form (B2B) ----------
  if (pageType === 'contact' && MODEL === 'b2b_lead') {
    document.addEventListener('DOMContentLoaded', function () {
      var form = document.querySelector('form[action*="contact"], form.contact-form, form#contact-form');
      if (!form) return;
      var started = false;
      form.addEventListener('focusin', function () {
        if (started) return; started = true;
        window.dataLayer.push({
          event:'contact_form_start',
          form_location: window.location.pathname
        });
      });
      form.addEventListener('submit', function () {
        var get = function (name) {
          var x = form.querySelector('[name="'+name+'"]'); return x ? x.value : '';
        };
        window.dataLayer.push({
          event:'contact_form_submit',
          form_location: window.location.pathname,
          industry: get('industry') || detectIndustry(),
          inquiry_type: get('inquiry_type'),
          company: get('company'),
          country: get('country')
        });
      });
    });
  }
})();
